fix(web): remove add target files option in fuzzjob view and fix controller
siemens/fluffi pull request #226
Opened 2020-07-15 10:12 UTC by jones718

- remove option in front end
- fix controller function according to the steps mentioned in the issue #215

2020-07-22 07:22 UTC, p4cx requested changes
Please adjust the status messages (Success, Error)

2020-07-22 07:22 UTC, p4cx commented on srv/fluffi/data/fluffiweb/app/controllers.py
> +        return "Success: Uploaded new target!", "success"
![image](https://user-images.githubusercontent.com/17053360/88145993-8feb1700-cbfb-11ea-84db-18d9feaf65dc.png)

Please remove one "Success".

2020-07-22 07:22 UTC, p4cx commented on srv/fluffi/data/fluffiweb/app/controllers.py
> +        return "Success: Uploaded new target!", "success"
This seems to be the case several times.

2020-07-22 12:52 UTC, jones718 commented on srv/fluffi/data/fluffiweb/app/controllers.py
> +        return "Success: Uploaded new target!", "success"
Thanks for pointing this out. I removed them.

2020-07-23 06:13 UTC, p4cx approved these changes

2020-07-23 06:28 UTC, merged